### ISSUE TITLE
retro pack init being called twice (bug)

### ISSUE THREAD

**Issue by mjkzy** [justinabellera/retro-pack#1]
https://github.com/justinabellera/retro-pack/blob/main/MWR%20(H2M)/patches.gsc#L7

doesn't need to be called here since it's in custom scripts folder and will be called by client's `init`. also, main is the wrong spot and init is better but mainly the first thing :P

**Comment by justinabellera** [comment]
thank you mikey 🫡

**Comment by justinabellera** [comment]
> https://github.com/justinabellera/retro-pack/blob/main/MWR%20(H2M)/patches.gsc#L7
> 
> doesn't need to be called here since it's in custom scripts folder and will be called by client's `init`. also, main is the wrong spot and init is better but mainly the first thing :P

The client isnt calling _retropack.gsc’s init() on its own for some reason, (files are placed in /scripts/mp/) is this the right folder?

**Comment by justinabellera** [comment]
fixed on version 0.9.5
